import type { ControlCenterData } from "@/lib/types";

export const mockControlCenterData: ControlCenterData = {
  dashboardState: {
    date: "2026-05-25",
    main_focus: "Cerrar la propuesta de esta semana y sostener la operación diaria.",
    energy_physical: "media",
    energy_mental: "alta",
    current_pressure: "moderada",
    today_main_action: "Enviar la propuesta final y definir el siguiente bloque de trabajo.",
    do_not_touch_today: "No abrir una iniciativa nueva antes de cerrar lo comprometido.",
    notes: "Datos de demostración. Conectá tu Google Sheet para usar información propia.",
  },
  projects: [
    {
      project_id: "ingresos",
      name: "Ingresos y ventas",
      status: "urgente",
      priority: "máxima",
      category: "Frente financiero",
      counter_id: "ventas_mes",
      accent: "amber",
      current_state: "Hay dos conversaciones comerciales activas y una propuesta por enviar.",
      next_action: "Enviar la propuesta prioritaria y fijar fecha de seguimiento.",
      blocker: "Falta confirmar alcance final.",
      last_updated: "2026-05-25 09:20",
      notes: "La caja inmediata ordena la prioridad del resto.",
      archived: false,
      archived_at: "",
      archived_reason: "",
    },
    {
      project_id: "producto",
      name: "Producto principal",
      status: "activo",
      priority: "alta",
      category: "Frente estratégico",
      counter_id: "sprint_actual",
      accent: "cyan",
      current_state: "Versión funcional lista para pruebas con usuarios iniciales.",
      next_action: "Completar la prueba guiada y registrar fricciones concretas.",
      blocker: "Dos validaciones pendientes.",
      last_updated: "2026-05-25 08:40",
      notes: "Priorizar señales reales antes de sumar funcionalidades.",
      archived: false,
      archived_at: "",
      archived_reason: "",
    },
    {
      project_id: "operacion",
      name: "Operación semanal",
      status: "activo",
      priority: "alta",
      category: "Frente operativo",
      counter_id: "racha_revision",
      accent: "green",
      current_state: "Agenda, entregas y revisión semanal están bajo control.",
      next_action: "Cerrar los pendientes administrativos antes del final del día.",
      blocker: "",
      last_updated: "2026-05-24",
      notes: "Sostiene el orden del sistema.",
      archived: false,
      archived_at: "",
      archived_reason: "",
    },
    {
      project_id: "contenido",
      name: "Contenido",
      status: "mantenimiento",
      priority: "media",
      category: "Frente de comunicación",
      counter_id: "",
      accent: "slate",
      current_state: "Calendario liviano preparado para la próxima publicación.",
      next_action: "Publicar una actualización breve cuando el frente principal esté cerrado.",
      blocker: "",
      last_updated: "2026-05-23",
      notes: "Modo mantenimiento.",
      archived: false,
      archived_at: "",
      archived_reason: "",
    },
    {
      project_id: "bienestar",
      name: "Bienestar",
      status: "activo",
      priority: "media",
      category: "Frente personal",
      counter_id: "",
      accent: "violet",
      current_state: "Rutina básica sostenida con margen para recuperación.",
      next_action: "Reservar un bloque sin reuniones al cierre de la tarde.",
      blocker: "",
      last_updated: "2026-05-25",
      notes: "Se mide como sostén, no como producción.",
      archived: false,
      archived_at: "",
      archived_reason: "",
    },
  ],
  archivedProjects: [
    {
      project_id: "archivo_demo",
      name: "Proyecto archivado",
      status: "archivado",
      priority: "baja",
      category: "Frente histórico",
      counter_id: "",
      accent: "slate",
      current_state: "Proyecto cerrado y conservado como referencia histórica.",
      next_action: "",
      blocker: "",
      last_updated: "2026-05-10",
      notes: "Ejemplo de frente que ya no ocupa el dashboard activo.",
      archived: true,
      archived_at: "2026-05-18",
      archived_reason: "Ciclo terminado.",
    },
  ],
  counters: [
    {
      counter_id: "ventas_mes",
      label: "Ventas del mes",
      current_value: 3,
      target_value: 8,
      unit: "ventas",
      last_updated: "2026-05-25",
      notes: "Tres acuerdos confirmados durante el mes.",
      type: "manual",
      start_date: "",
      reset_date: "",
      auto_calculate: false,
      derived_from: "current_value",
      project_id: "ingresos",
      accent: "amber",
    },
    {
      counter_id: "sprint_actual",
      label: "Día de sprint",
      current_value: 6,
      target_value: 14,
      unit: "días",
      last_updated: "2026-05-20",
      notes: "Se calcula desde la fecha de inicio.",
      type: "date_based",
      start_date: "2026-05-19",
      reset_date: "",
      auto_calculate: true,
      derived_from: "start_date",
      project_id: "producto",
      accent: "cyan",
    },
    {
      counter_id: "racha_revision",
      label: "Racha de revisión",
      current_value: 4,
      target_value: 21,
      unit: "días",
      last_updated: "2026-05-22",
      notes: "Se reinicia al registrar un nuevo comienzo.",
      type: "date_based",
      start_date: "",
      reset_date: "2026-05-22",
      auto_calculate: true,
      derived_from: "reset_date",
      project_id: "operacion",
      accent: "green",
    },
  ],
  updatesLog: [
    {
      timestamp: "2026-05-25 09:20",
      project_id: "ingresos",
      type: "next_action",
      summary: "Propuesta prioritaria lista para enviar",
      details: "El alcance quedó reducido a lo esencial para poder cerrar decisión esta semana.",
      mood: "enfocado",
      energy: "alta",
      source: "demo",
    },
    {
      timestamp: "2026-05-25 08:40",
      project_id: "producto",
      type: "milestone",
      summary: "Versión funcional preparada para prueba",
      details: "La prueba busca fricciones operativas antes de sumar nuevas capacidades.",
      mood: "claro",
      energy: "alta",
      source: "demo",
    },
    {
      timestamp: "2026-05-24 18:00",
      project_id: "operacion",
      type: "daily_close",
      summary: "Revisión semanal completada",
      details: "Se ordenaron próximos pasos y se movieron tareas sin impacto fuera del foco.",
      mood: "estable",
      energy: "media",
      source: "demo",
    },
    {
      timestamp: "2026-05-23",
      project_id: "contenido",
      type: "maintenance",
      summary: "Calendario de publicaciones reducido",
      details: "Contenido queda liviano mientras el frente comercial requiere atención.",
      mood: "sereno",
      energy: "media",
      source: "demo",
    },
  ],
  dailyCheckins: [
    {
      date: "2026-05-25",
      type: "checkin",
      physical_energy: "media",
      mental_energy: "alta",
      summary: "El día tiene una decisión principal clara y margen suficiente.",
      main_action: "Enviar propuesta final.",
      tomorrow_action: "Revisar respuesta y ajustar el sprint.",
      notes: "No dispersar energía en tareas nuevas.",
    },
    {
      date: "2026-05-24",
      type: "cierre",
      physical_energy: "media",
      mental_energy: "media",
      summary: "La revisión dejó prioridades claras para empezar la semana.",
      main_action: "Preparar la propuesta.",
      tomorrow_action: "Enviar y dar seguimiento.",
      notes: "Cerrar antes de ampliar.",
    },
  ],
  config: [
    {
      key: "source_of_truth",
      value: "Google Sheets",
      notes: "Base editable para el dashboard.",
    },
    {
      key: "dashboard_goal",
      value: "Mostrar el presente primero.",
      notes: "Demo genérica del template.",
    },
  ],
  source: "mock",
  warning: "Modo demo activo / configurá Google Sheets para usar tus datos",
  generatedAt: "2026-05-25T12:00:00-03:00",
};
